version: '3.4'

services:
  consumer:
    image: dan07consumer:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ST-KafkaConsumer"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_consumer$
    volumes:
      - C:\Apps\SimpleTalk\ST-KafkaProducer\ST-KafkaConsumer:/app
      - C:\Apps\SimpleTalk\ST-KafkaProducer:/src
      - C:\Users\daniel.moldovan\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_consumer$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_consumer$ \"/app/bin/Debug/netcoreapp3.1/ST-KafkaConsumer.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  producerapi:
    image: dan07producerapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ST-KafkaProducer"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_producerapi$
    volumes:
      - C:\Apps\SimpleTalk\ST-KafkaProducer\ST-KafkaProducer:/app
      - C:\Apps\SimpleTalk\ST-KafkaProducer:/src
      - C:\Users\daniel.moldovan\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_producerapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_producerapi$ \"/app/bin/Debug/netcoreapp3.1/ST-KafkaProducer.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
